### ISSUE TITLE
v2.1.2: After update from v2.1.1 nothing was working anymore

### ISSUE THREAD

**Issue by RkcCorian** [arteck/ioBroker.fullybrowser#102]
Short: v2.1.2 is not working at all (even beeing green)
More details: 2.1.1 is running stable. After installation of v2.1.2 yesterday no datapoint has been updated anymore and no command that I send was executed anymore and this even the adapter went green. I even retyped the Passwort again in the config and restarted everything (tablet with fully, ioBroker, ioBroker-Adapter) but nothing helped. Therefore I downgraded again to v2.1.1 and directly after this downgrade it is instantly working again.

**Comment by arteck** [comment]
LOG?

**Comment by cradermacher** [comment]
Nearly the same to me. Installed Version is 2.1.2.
The state war read correctly and was updated, but no command was sent.
With exec curl i can start/stop the screensaver, but fully adapter doesn´t work

I don´t know how to sent a log and which log do you need?

Pleas tell me which log do you need.

**Comment by cradermacher** [comment]
In my case, the Version 2.1.1 doesn´t work.

**Comment by cradermacher** [comment]
it is a Fire HD 10 from 2021, not the actual Version.
But i think not the Tabelt is the Problem. 
With a REST call i can switch the tablet on/off, only with the adapter it doesn´t work.

**Comment by RkcCorian** [comment]
I have a "samsung galaxy tab a7". I also think it must be the adapter. The only thing that was changed by me is the adapter version from v2.1.1 to v2.1.2, then the problem happens like described by @cradermacher . When I go back to v2.1.1 it is working fine immediately.
When I have more time I can update again and send the log...

**Comment by arteck** [comment]
this all works for me
![grafik](https://user-images.githubusercontent.com/6681528/179908831-a2e738b2-d67f-4c07-a2e1-386d03742ee7.png)

check plz the privileges from fully in tab settings..

**Comment by RkcCorian** [comment]
> this all works for me ![grafik](https://user-images.githubusercontent.com/6681528/179908831-a2e738b2-d67f-4c07-a2e1-386d03742ee7.png)
> 
> check plz the privileges from fully in tab settings..

I checked but is OK from my understand. To not miss anything... which configuration your are pointing to?

**Comment by RkcCorian** [comment]
@arteck : Anything new here? Refer also to https://github.com/arteck/ioBroker.fullybrowser/issues/109

**Comment by arteck** [comment]
LOG ?

**Comment by RkcCorian** [comment]
If I see it right the adapter has a problem with special characters. I checked the log and the passwort is at one position wrong. I have a "!" inside my passwort and at this position in the string stands "undefined". I heavily assume that this is causing the trouble as well for others that uses special characters in the passwort.

![image](https://user-images.githubusercontent.com/79741077/199087872-8b6f84a6-12f7-42c8-9a40-1eae47099077.png)

**Comment by RkcCorian** [comment]
@arteck : Do you had time to confirm / fix my evaluation? Greetings!

**Comment by arteck** [comment]
check GIT version now

**Comment by RkcCorian** [comment]
@arteck : Many thanks! Checked with 2.1.6 and it works
