### ISSUE TITLE
Password handling faulty in v.2.1.2

### ISSUE THREAD

**Issue by Svenibaer** [arteck/ioBroker.fullybrowser#109]
I've updated my ioBroker system completly. So also the fullybrowser adapter from v.2.0.1 to v.2.1.2.
The adapter worked, the connections to several tablets could be established. But the fullybrowser running on the tablets didn't execute any command like screenOn - as before.
I turned on debug logging and saw, that the password handling is faulty/ corrupt:

`Send http://10.1.50.31:2323/?cmd=screenOn&password=nT0i3ym51undefined`

My password is 10 characters long - the last one is an exclamation point (!) - but is missing/ filled with 'undefined'

1. I've retyped the passwords in the adapter settings -> same result
2. I've deleted all devices in adapter settings and set them up again from scratch -> same result
3. I've deleted the adapter and installed it again, set up the devices/ parameters again -> same result
4. I've changed my password, only concerning the last character from "!" to "A" on the devices and in the adapter settings -> works as expected again. Hurrah.

Maybe other users facing the same problem so a fix would be great!

Thanks in advance
Sven

P.S.: Thanks for your good work!!!

**Comment by RkcCorian** [comment]
@Arteck: Redundant to https://github.com/arteck/ioBroker.fullybrowser/issues/102, but I guess it explains the root cause why v2.1.2 does not work and no commands are executed

**Comment by arteck** [comment]
check GIT version now

**Comment by RkcCorian** [comment]
@Svenibaer : FYI, I checked with 2.1.6 and it is working, refer also to https://github.com/arteck/ioBroker.fullybrowser/issues/102
@arteck : I guess you can close both issues
