### ISSUE TITLE
Naming in Objecst

### ISSUE THREAD

**Issue by gaga191281** [arteck/ioBroker.fullybrowser#114]
Because I have 11 devices running it would be more than convenient to have the opportunity to name the devices in the 'objects'-view. 
![image](https://user-images.githubusercontent.com/60061155/198209293-9f4ca7a8-ff76-4ffe-ab7e-2b11e5f8096e.png)
Currently it is not possible to add a name or **add the device to room**, which would even be better.

**Comment by arteck** [comment]
check new version
