### ISSUE TITLE
Update auf 0.1.15 geht nicht

### ISSUE THREAD

**Issue by Ridesa** [arteck/ioBroker.fullybrowser#12]
Das Update auf 0.1.15 läuft ohne Fehler durch Adapter bleibt aber bei 0.1.13 bei mir.

**Comment by Ilovegym66** [comment]
Hier startet er das update, und beendet ohne Installation. Bleibt auf der alten Version.

**Comment by intruder7777** [comment]
dito bei mir uodate auf 0.1.15 bleibt danach aber auf 0.1.13 und 0.1.15 wird wieder angeboten

**Comment by arteck** [comment]
fixed
