### ISSUE TITLE
State "fullybrowser.0.192_168_0_144. Info.timestamp" has no existing object

### ISSUE THREAD

**Issue by Toysman** [arteck/ioBroker.fullybrowser#121]
Hallo,
Fullybrowser v. 2.1.2 generiert diese Info im Minutentakt - wie kann dieses umgangenwerden?
In den Datenpunkten des Tablets ist "timestamp" nicht zu finden.
Danke & Gruß

Hello,
Fullybrowser v. 2.1.2 generates this info every minute - how can this be bypassed?
In the tablet's datapoints "timestamp" is not found.

Thanks & greetings

<img width="1170" alt="Bildschirm­foto 2022-11-25 um 18 00 01" src="https://user-images.githubusercontent.com/76917387/204138125-c0337551-ba68-4dbf-bd4e-d2405a7a713e.png">

**Comment by arteck** [comment]
lösche das object
