### ISSUE TITLE
missing objects

### ISSUE THREAD

**Issue by Boronsbruder** [arteck/ioBroker.fullybrowser#132]
Ich habe immermal wieder folgende Warnung im Log:
`2023-01-08 16:31:18.435 - warn: fullybrowser.0 (27282) State "fullybrowser.0.192_168_116_2.Info.foregroundActivity" has no existing object, this might lead to an error in future versions`

Nachdem ich den Objectbaum gelöscht und die INstanz neugestartet hatte, wurde nach dem Neustart noch folgende angezeigt
`2023-01-09 15:56:34.896 - warn: fullybrowser.0 (27282) State "fullybrowser.0.info.connection" has no existing object, this might lead to an error in future versions`
Hier ist wahrscheinlich ein Tippfehler? -> **info** statt **Info**

**Comment by arteck** [comment]
das sind 2 unterschiedliche Datenpunkte....seh ich gerade
der eine wird generiert.. und kommt unter 192_168_116_2.Info der andere ist der info vom adapter ..
