### ISSUE TITLE
feature request: Reboot Device

### ISSUE THREAD

**Issue by DuschdrBabbe** [arteck/ioBroker.fullybrowser#138]
Possibility to restart the device via iobroker...

In Fullybrower there ist that option...

Grüßle
Pascal

**Comment by arteck** [comment]
the device ?? app yes ..i know

**Comment by pacco81** [comment]
The Developer of FullyKiosk gave this hint:

"REST API
 cmd=rebootDevice"

**Comment by arteck** [comment]
use command DP

**Comment by arteck** [comment]
check Version 3.0.2
