### ISSUE TITLE
Open App

### ISSUE THREAD

**Issue by Marsx79** [arteck/ioBroker.fullybrowser#14]
For what is "startApplication"?
How can I use this?

If i use this for the Sonos App:
intent:#Intent;launchFlags=0x10000000;component=com.sonos.acr/.SonosLaunchActivity;end
Nothing happens.

In ioBroker Vis it works.

**Comment by arteck** [comment]
startApplication is for application start.. but this is from FullyBrowser direct start..
plz check this function direct from fully
