### ISSUE TITLE
feature request: Motion Detecotor de/aktivieren

### ISSUE THREAD

**Issue by R-Lin3r** [arteck/ioBroker.fullybrowser#141]
Hallo,
wollte fragen ob es möglich wäre die Bewegeungserkennung ein bzw. auszuschalten, da sie bspw. wenn niemand da ist unnnötig mehr strom nutzt. Da könnte man per Anwesenheitserkennung den Datenpunkt dann schalten.

Danke sehr für den gelungen und bisher absolut bugfreien Adapter :)
 
Grüße Jens

**Comment by arteck** [comment]
na wen aber keine Bewegung da ist ..dann passiert auch nichts.. verstehe nicht warum du die Bewegeungserkennung zusätzlich abschalen willst....

was auch geht musst du nur per command selber machen

**Comment by R-Lin3r** [comment]
wie schon ausgeführt, mit aktiver motion dedection ist der akku im tablet 4 mal schneller entladen. ging einfach nur um eine winzige optimierung.

wenn man das per command macht, weiß ich leider nicht. bin nur ein skriptkiddi und wenn es fpr eine funktion kein datenpunkt gibt, dann kann ich das nicht steuern :)

**Comment by Wolfi913** [comment]
Vielleicht hilft dir mein Blockly. Bei mir funktionierts, bspw zum Ausschalten der MotionDetection während der TV läuft, einwandfrei.

[motiondetection.txt](https://github.com/arteck/ioBroker.fullybrowser/files/13243198/motiondetection.txt)

**Comment by arteck** [comment]
check Version 3.0.2
