### ISSUE TITLE
Info.audioVolumes has no existing object

### ISSUE THREAD

**Issue by Boronsbruder** [arteck/ioBroker.fullybrowser#148]
Seit dem letzten FullyBrowser-Update (vom 20.07.)
werden 
`2023-07-21 16:00:33.821 - warn: fullybrowser.0 (1427047) State "fullybrowser.0.192_168_116_2.Info.audioVolumes" has no existing object, this might lead to an error in future versions`
gelogged

**Comment by arteck** [comment]
lösche diesen ordner fullybrowser.0.192_168_116_2.Info

der wird dan neu erstellt..
