### ISSUE TITLE
Warnmeldung bei Version 3.0.6

### ISSUE THREAD

**Issue by jack-blackson** [arteck/ioBroker.fullybrowser#177]
Hallo!

Mir ist aufgefallen, das ich seit dem Uprade heute auf 3.0.6 folgende Warnmeldung vom admin Adapter bekomme:

```
fullybrowser has an invalid jsonConfig: [{"instancePath":"/items/_tab_Start/items/tableDevices/items/6","schemaPath":"#/definitions/passwordProps/additionalProperties","keyword":"additionalProperties","params":{"additionalProperty":"title"},"message":"must NOT have additional properties"},{"instancePath":"/items/_tab_Start","schemaPath":"#/properties/items/patternProperties/%5E.%2B/allOf/8/if","keyword":"if","params":{"failingKeyword":"then"},"message":"must match \"then\" schema"}]
--
```

Kann ich hier was machen? Admin ist auf 6.12.0, json controller auf 5.0.16

**Comment by Ilovegym66** [comment]
Hi, ist n Fehler von Admin, in Version 6.12.4 behoben.

**Comment by Brainbug01** [comment]
> Hi, ist n Fehler von Admin, in Version 6.12.4 behoben.

Ich hab Admin 6.12.4 am laufen und der Fehler ist dort nicht behoben.

**Comment by arteck** [comment]
Admin Problem ist bekannt
