### ISSUE TITLE
setting bat level to zero when wifi signal is broken at non zero bat level

### ISSUE THREAD

**Issue by tmaul1968** [arteck/ioBroker.fullybrowser#197]
Hi,
the latest change (setting bat level to zero when fully is offline) works correct but isn't the truth.
Even if fully is offline when wifi signal is broken from the router side the bat level will be set to zero for the time being offline even if true bat level is non zero.

Cheers

**Comment by arteck** [comment]
this is correct but.. when the device is offline is the battery in undefined state.. i think its better like 0

**Comment by Wildbill-Z** [comment]
For my opinion, 0 is wrong. The last known value is the most correct one. If setting to 0 for example it will start charging via script, even if battery of device isn't below threshold, but iobroker now thinks, it would be 0. Also, scripts or adapters as device-watcher now will send two warn messages, one for the device being offline and another for the "empty" battery. Maybe it should be made as a user decision via settings?!

What was the intention to set the value to 0 if device is offline?

**Comment by arteck** [comment]
install GIT version and check settings

**Comment by Wildbill-Z** [comment]
Works as expected. I think, issue may be closed.
