### ISSUE TITLE
Battery - Abfrage - - Wert inkorrekt

### ISSUE THREAD

**Issue by Nuggelbeb** [arteck/ioBroker.fullybrowser#206]
Hallo,

ich habe ein

_Huawei MediaPad T2 10.0 Pro mit Android 5.1 und Fully Browser Version 1.54.1 PLUS Lizenz,_

sowie einen
_ioBroker mit dem Adapter fully-browser Version 3.0.12_

Wenn der Adapter neu gestartet wurde, die App Fully Browser ebenfalls neu gestartet wurde, wird mir der Wert der Batterie unter Objekte "batteryLevel" korrekt angezeigt.

![Screenshot 2024-03-05 182119](https://github.com/arteck/ioBroker.fullybrowser/assets/46019514/86f7dc06-0fc0-4262-ba39-69fcfeb9a7d1)

Nach einer unbestimmten Zeit wird plötzlich der Wert mit "-1 %" angezeigt und ebenfalls bei der Batterietemperatur "-1°C".

![Screenshot 2024-03-05 181625](https://github.com/arteck/ioBroker.fullybrowser/assets/46019514/a7e7a47a-0127-46f4-a47b-e606d85546e3)

Leider ist dadurch die Ladesteuerung nicht möglich.

Was kann ich tun?
Worin liegt das Problem?

Danke im Voraus.

**Comment by arteck** [comment]
kann ich nicht nachvollziehen.. bei 5 Tablets..
