### ISSUE TITLE
TTS: Qualität schlechter als direkt / Umlaute gehen nicht

### ISSUE THREAD

**Issue by Fiiti** [arteck/ioBroker.fullybrowser#21]
Hi,
1.) Qualtät
Nutze ich die WEB-API direkt um einen Text sprachlich auszugeben ist die Qualität recht gut.
`http://192.168.123.123:2323/?cmd=textToSpeech&text=%22Der%20externe%20Alarm%20wurde%20deaktiviert.%20Es%20gab%20einen%20verpassten%20Anruf.%22&locale=de_DE&password=strenggeheim&type=json`

Verwende ich hingegen das iobroker Objekt 
fullybrowser.0.192_168_123_123.Commands.textToSpeech
Und fülle es per copy/paste oder in JS ist der Beispieltext oben vor allem bei "...externe Alarm..." 
nicht schön. Zu schnell/ungenau.

2.) Umlaute
Testweise habe ich den Parameter "&locale=de_DE" im WebAufruf entfernt => habe ich keinen Unterschied in der Qualität dazu festgestellt, als wenn ich ihn drinnen lasse. Ausgabe war gleich gut - macht nur bei Umlauten Schwierigkeiten.

=> Dieser Parameter sollte für die Umlaute mindestens also noch per Auswahl in den ioBroker Settings einstellbar sein und mitgegeben werden.

Gruß,

Fii

**Comment by arteck** [comment]
es liegt nicht an dem &locale=de_DE parameter.. 
wenn du im browser ein statement absetzt dann passiert da noch was.. muss ich suchen..

p.s: sry dass ich mich so spät melde
