### ISSUE TITLE
Anfrage für weiteres Feature

### ISSUE THREAD

**Issue by peoples0815** [arteck/ioBroker.fullybrowser#24]
HI,
ich wollte mal anfragen ob angedacht ist die Display Helligkeit auch über den Adapter steuerbar zu machen?

**Comment by FredF63** [comment]
Hi,
das geht doch schon... siehe 
https://github.com/arteck/ioBroker.fullybrowser/wiki/Befehle-absetzen

**Comment by peoples0815** [comment]
Ok das habe ich tatsächlich überlesen, dann stellt sich natürlich die Frage ob hier wirklich die Sinnigkeit eines extra Datenpunktes gegeben ist.

**Comment by peoples0815** [comment]
Leider funktioniert das bei mir nicht. Da es aber nicht das Einzige ist was nicht funktioniert und auch immer wieder die Verbindung verlohren geht, liegt das wahrscheinlich nicht am Adapter
