### ISSUE TITLE
States unter "info

### ISSUE THREAD

**Issue by bemme0815** [arteck/ioBroker.fullybrowser#25]
Hi.

Erstmal danke für den coolen Adapter.
Leider stehen bei mir unter "info" nur 2 states: error
              Please login

Login ist aber korrekt, da ich den auch im Browser korrekt verwenden kann und mir da alle States angezeigt werden.
Woran kann das liegen?

Vielen Dank vorab

**Comment by arteck** [comment]
sonderzeichen im Passwort??
