### ISSUE TITLE
Anfrage für Feature

### ISSUE THREAD

**Issue by TheBermud** [arteck/ioBroker.fullybrowser#28]
Hallo, 
wäre es möglich einen Datenpunkt zu schaffen, mit dem man die Seite vom Fully refreshen kann? In "Toolbars and Appearence" in den Einstellungen kann man eine Action Bar einstellen wo ein Refresh Button sichtbar wird. Wäre super wenn es den als Datenpunkt mit Tastendruck gebe ähnlich den anderen wie restart App. 

Liebe Grüße

**Comment by arteck** [comment]
![grafik](https://user-images.githubusercontent.com/6681528/74604594-c7d7b680-50bf-11ea-8a15-e6f528a94957.png)

**Comment by TheBermud** [comment]
Damit läd man die Startseite neu und nicht die aktuelle Seite. 
Wenn ich damit die aktuelle Seite neu Laden möchte, werde ich beim ersten drücken auf die Startseite geleitet und beim zweiten drücken wird neu geladen und dann muss ich wieder dahin zurück wo ich war. 
Man kann im Fully "Pull to Refresh" einstellen oder einen sichtbaren Button zum refreshen, was ich beides nicht optimal finde.  Dies ist über die Datenpunkte aktuell nicht möglich und darauf bezog sich meine Anfrage.

**Comment by xXBJXx** [comment]
es gibt soweit ich weiß keine Möglichkeit die aktuelle Seite neu zuladen da es in den Einstellungen vom Fully auch kein Button oder so dafür gibt. Es gibt nur die Möglichkeit es einzuschalten (Enable Pull to Refresh) und wie es es da auch stecht (Pull to Refresh = Zum Aktualisieren ziehen ) über den Adapter kann man leider die Funktion im Browser nicht ausführen.

**Comment by TheBermud** [comment]
In den Einstellungen unter "Toolbars and Appearence" kann man die "Action Bar" aktivieren und dort "Show refresh Button" einstellen. Da es diesen Button gibt hatte ich gehofft, dass man das auch in Iobroker als Datenpunkt einstellen kann
