### ISSUE TITLE
keine aktualisierung nach Update auf 2.0.0

### ISSUE THREAD

**Issue by Farmer-cb** [arteck/ioBroker.fullybrowser#38]
Hallo
nach dem Update von 1.0.4 auf 2.0.0 aktualisieren sich die Daten nicht mehr, es gibt auch keine Fehlermeldung im Log
debug-log liefere ich nach

**Comment by canim60** [comment]
Ich hab gedacht ich wäre der einzige und suche wie so ein verückter nach das Problem..., Meine Device Daten werden auch nicht aktualisiert, gemerkt habe ich es, weil ich über den Akkustand das Tablet auflade ..

**Comment by BassT23** [comment]
Bei mir auch.
App auf 1.41 - Daten werden nicht aktualisiert.

**Comment by BassT23** [comment]
Fehler gefunden:

Problem ist der Updateintervall in den Adapter Settings.

Dieser ist jetzt in sec (nicht mehr msec)
Die Zeit war aber noch auf 60000.

Die Updatezeit auf 60 gestellt und die Daten kommen wieder Zeitnah an 🙃

**Comment by BassT23** [comment]
Update:

Das ändern der Intervall Zeit von ms in sec ist nur der erste Teil.

Desweiteren wurden auch Veränderungen in der Datenstruktur vorgenommen.
Zb wird der Datenpunkt "isScreenOn" nicht mehr bedient, bzw durch "ScreenOn" abgelöst.
Leider werden alte, nicht mehr verwendete Datenpunkte nicht erkenntlich gemacht.

Meine Lösung: 
- Adapter Stoppen
- Alle Datenpunkte löschen
- Adapter wieder neu starten

Dann habt ihr wieder alle funktionierenden Datenpunkte. Nicht vergessen eure Scripte neu anzupassen.

Grüße BassT23
