### ISSUE TITLE
Automatic update is stopped, if one update failed

### ISSUE THREAD

**Issue by zapccu** [arteck/ioBroker.fullybrowser#39]
If one update of fully values fails, update is stopped forever.
Restart of adapter instance is solving the problem.

**Comment by arteck** [comment]
i know this problem but i dont know why
plz restart the adapter once a day
![grafik](https://user-images.githubusercontent.com/6681528/102010848-eee33100-3d40-11eb-9416-f83d745221c0.png)

**Comment by arteck** [comment]
check plz new GIT version
