### ISSUE TITLE
compact mode failing 

### ISSUE THREAD

**Issue by handy80** [arteck/ioBroker.fullybrowser#40]
Hi using fullybrowser adapter now for some time and I recently? got errors using compact mode:
Source: 

host.ioBroker.compactgroup1

`Cannot start fullybrowser.0 in compact mode. Fallback to normal start! : ENOENT: no such file or directory, open '/opt/iobroker/node_modules/iobroker.fullybrowser/node_modules/follow-redirects/index.`

there is a prceding error without source 
`ndefined`

Is that a know issue (even maybe for some time) and do you need more info to fix this?

PS: just updated fullybrowser today to version 2.0.2. I think the error appears since then.

kind regards

**Comment by arteck** [comment]
ahh i forgot it after refactoring..

**Comment by Apollon77** [comment]
@handy80 Please try to restart the js.controlelr (or at least the affected compact group). Is ot then happening again?

Directly after an update it can happen in compact mode that modules are mixed and not fully reloaded as required by the update

**Comment by handy80** [comment]
let's close the issue. it's running again. Can't say why. I think I did not receive a new version (still 2.0.2.) after a restart of the system (for other reasons) the instance is running stable again. thanks!
