### ISSUE TITLE
js-controller 3.2.7

### ISSUE THREAD

**Issue by WaJoWi** [arteck/ioBroker.fullybrowser#42]
State "fullybrowser.0.info.connection" has no existing object, this might lead to an error in future versions

---

**System data:**

Platform: linux
Distribution: Debian GNU/Linux
Architecture: x64
Model: Intel(R) Celeron(R) CPU J3455 @ 1.50GHz
RAM: 4 GB
Node.js: v12.20.1
NPM: v6.14.10
JS-Controller (1): 3.2.7
Admin: 4.2.1
fullyBrowser: 2.0.2

> *created by ioBroker.info*

**Comment by arteck** [comment]
test now plz

**Comment by arteck** [comment]
fixed
