### ISSUE TITLE
updateDeviceERROR 

### ISSUE THREAD

**Issue by pacman13** [arteck/ioBroker.fullybrowser#44]
Hallo, 

ich habe derzeit drei "fullyBrowser Installationen (plus)" welche ich mit einer ioBroker Instanz steuere. 

Eine Installation davon (Android 8 basierter Spiegel) is meistens offline, also im standby. Solange das der Fall ist, erzeugt das  dann jede Minute eine Meldung:

fullybrowser.0 | 2021-03-08 16:16:35.204 | warn | (32274) updateDeviceERROR 192.168.178.29
fullybrowser.0 | 2021-03-08 16:15:34.676 | warn | (32274) updateDeviceERROR 192.168.178.29
fullybrowser.0 | 2021-03-08 16:14:34.167 | warn | (32274) updateDeviceERROR 192.168.178.29
fullybrowser.0 | 2021-03-08 16:13:33.784 | warn | (32274) updateDeviceERROR 192.168.178.29
fullybrowser.0 | 2021-03-08 16:12:33.023 | warn | (32274) updateDeviceERROR 192.168.178.29

Ein Tablet (ebenfalls Android 8), erzeugt keine Meldung wenn es im Ruhezustand ist. Hat jemand eine Idee ob mann die Meldung ggf. unterdrücken oder ob es an unterschiedlichen Konfigurationen liegen kann?

Danke !

**Comment by arteck** [comment]
wenn es keine Verbindung hergestellt erden kann zu dem tabled dann bekommst du eine Warnung dass w da was nicht stimmt

**Comment by arteck** [comment]
https://github.com/arteck/ioBroker.fullybrowser/issues/45
