### ISSUE TITLE
no client connection after update to 2.0.6

### ISSUE THREAD

**Issue by 3d-droide** [arteck/ioBroker.fullybrowser#45]
after the update from 2.0.4 to 2.0.6, a connection to the tablet is no longer possible. the data point "isFullyAlive" is false and "updateDeviceERROR" appears in the log file.
after a downgrade to 2.0.4 everything works again.

**Comment by Matt77CHE** [comment]
... Ist bei mir auch so;
Immer wieder deviceerror und alive false...

**Comment by tobasium** [comment]
ich schließe mich dem Problem ebenfalls an 2.0.5 läuft danach is fullyAlive nur noch auf false

**Comment by arteck** [comment]
ohh Leute... EINSTELLUNGEN überprüfen... da ist ein timeout zum einstellen
