### ISSUE TITLE
4807) updateDeviceERROR 

### ISSUE THREAD

**Issue by naesle** [arteck/ioBroker.fullybrowser#46]
Since update to 2.06 I get permanent message 4807) updateDeviceERROR 192.168.x.xx
When roll previous version everything is OK

**Comment by Frank1604** [comment]
Same problem here.

![grafik](https://user-images.githubusercontent.com/10420590/112308968-09636980-8ca3-11eb-8761-41cdf1e8dbc8.png)

Full log entry:
` (9488) Generate State problem 192_168_178_56     {'message':'timeout of 10ms exceeded','name':'Error','stack':'Error: timeout of 10ms exceeded\n    at createError (/opt/iobroker/node_modules/axios/lib/core/createError.js:16:15)\n    at RedirectableRequest.handleRequestTimeout (/opt/iobroker/node_modules/axios/lib/adapters/http.js:280:16)\n    at Object.onceWrapper (events.js:420:28)\n    at RedirectableRequest.emit (events.js:314:20)\n    at Timeout._onTimeout (/opt/iobroker/node_modules/follow-redirects/index.js:166:13)\n    at listOnTimeout (internal/timers.js:554:17)\n    at processTimers (internal/timers.js:497:7)','config':{'url':'http://192.168.178.56:2323/?cmd=deviceInfo&type=json&password=xxxxxxxx','method':'get','headers':{'Accept':'application/json, text/plain, */*','User-Agent':'axios/0.21.1'},'transformRequest':[null],'transformResponse':[null],'timeout':10,'xsrfCookieName':'XSRF-TOKEN','xsrfHeaderName':'X-XSRF-TOKEN','maxContentLength':-1,'maxBodyLength':-1},'code':'ECONNABORTED'}`

**Comment by arteck** [comment]
check Adapter Settings.. and set Timeout correct
