### ISSUE TITLE
Generateb state problem in log

### ISSUE THREAD

**Issue by Matt77CHE** [arteck/ioBroker.fullybrowser#50]
Hallo;
Ich habe seit einiger Zeit diese Log Einträge:

<html><body>

fullybrowser.0 | 2021-05-12 20:14:32.327 | warn | (16540) updateDeviceERROR 192.168.1.50
-- | -- | -- | --
fullybrowser.0 | 2021-05-12 20:14:10.316 | warn | (16540) updateDeviceERROR 192.168.1.50
fullybrowser.0 | 2021-05-12 20:14:09.261 | warn | (16540) Generate State problem 192_168_1_50     {"message":"timeout of  2000ms exceeded","name":"Error","stack":"Error: timeout of 2000ms  exceeded\n    at createError (/opt/iobroker/node_modules/axios

</body>
</html>

Was hat das mit dem "generate state problem" auf sich?

**Comment by arteck** [comment]
dein Tablet antwortet nicht in den angegebenen timeout zeit.. stell den timeout höher
