### ISSUE TITLE
Dropdown in popup view

### ISSUE THREAD

**Issue by Matt77CHE** [arteck/ioBroker.fullybrowser#51]
Hallo, 
ich habe das Problem, dass Dropdown-Listen im Popup (View) nicht nutzbar sind (lassen sich nicht öffnen und auswählen).
Ich habe so ziemlich alle verschiedenen Dropdown ausprobiert - im normalen Browser funktionieren sie jeweils, im FKB jedoch nicht...
der Switch der ebenfalls separat im popup noch da ist, funktioniert.

- wieso fuktionieren die Dropdown nicht?

**Comment by arteck** [comment]
hä.... wo von redest du ???

**Comment by Matt77CHE** [comment]
....also;
Hier das Bild der view in der die Dropdown sind:

![Klima](https://user-images.githubusercontent.com/73795309/119339856-ffa1b680-bc91-11eb-8616-7407a894506b.jpg)

Hier das Bild mit dem Button für die View in Popup - und eben in diesem Popup kann ich nun die Dropdown nicht mehr anwählen:

![Klima_2](https://user-images.githubusercontent.com/73795309/119340026-3972bd00-bc92-11eb-947e-81e6ab8d2880.jpg)

**Comment by arteck** [comment]
und was hat das mit dem Adapter zu tun ?? das ist Visu

**Comment by Matt77CHE** [comment]
Deiner sehr charmanten Antwort zufolge scheinbar nichts...
