### ISSUE TITLE
Feature Request "getAudioVolume"

### ISSUE THREAD

**Issue by IllegalDuke** [arteck/ioBroker.fullybrowser#54]
Hallo,

ich würde es sehr begrüßen, wenn (weitere) get Befehle implementiert werden würden.
Speziell benötige ich die aktuelle Audio Volume, damit ich vor dem setzen der Audio Volume die bisherige Volume abfragen und speichern kann.
Laut Handbuch von Fully kann dies mit "void fully.getAudioVolume(int streamType)   // ver. 1.27+" umgesetzt werden.

Weiterhin sehe ich "fully.getStringSetting(String key)" als sinnvoll an.

Vielen Dank im Voraus.
Daniel

**Comment by arteck** [comment]
du kannst alle commands auch im dem Datenpukt realisieren.. 
lesen bitte
[**https://github.com/arteck/ioBroker.fullybrowser/wiki/Befehle-absetzen**](https://github.com/arteck/ioBroker.fullybrowser/wiki/Befehle-absetzen)
