### ISSUE TITLE
Update device error

### ISSUE THREAD

**Issue by KayThe95** [arteck/ioBroker.fullybrowser#56]
Hallo,

ich habe oft einen Update-Device Error in meinem Log, an was könnte das liegen?

<html>
<body>

fullybrowser.0 | 2021-09-09 13:54:05.817 | warn | updateDeviceERROR 192.168.178.45
-- | -- | -- | --
fullybrowser.0 | 2021-09-09 13:53:05.806 | warn | updateDeviceERROR 192.168.178.45
fullybrowser.0 | 2021-09-09 13:52:05.698 | warn | updateDeviceERROR 192.168.178.45
fullybrowser.0 | 2021-09-09 13:51:05.486 | warn | updateDeviceERROR 192.168.178.45

</body>
</html>

**Comment by arteck** [comment]
das ein WARNING.. das Gerät ist nicht erreichbar..
