### ISSUE TITLE
Issue #57 noch nicht gelöst

### ISSUE THREAD

**Issue by Schmetterfliege** [arteck/ioBroker.fullybrowser#58]
Hi,

Mein log wird leider ebenfalls von den Messages aus Issue #57 vollgespammt.
Die erwähnte Lösung - datapoint löschen und Adapter neu starten - hilft wie in den Kommentaren dort leider nicht.
Der Punkt wird wieder neu erstellt - mit dem selben Fehler.

**Comment by stony2k** [comment]
Gleiche Problem hier. Ein Neustart vom Adapter hat auch bedingt geholfen. Die Log wird wieder zugespammt.

**Comment by arteck** [comment]
leute

adapter stop
lösche alle objecte des adapter
start des adapter

die objecte werden jetzt alle nochmal angelegt.. mit den richtigen angaben
