### ISSUE TITLE
Change loglevel with restart

### ISSUE THREAD

**Issue by meistermopper** [arteck/ioBroker.fullybrowser#59]
Every time the adapter is restarted, the loglevel is set to info, although it was previously set to error.

**Comment by arteck** [comment]
which admin version ??

**Comment by meistermopper** [comment]
admin 5.1.25
fully 2.0.9

**Comment by arteck** [comment]
the log level is a settings from admin.. 
check plz 

`iobroker fix`

**Comment by meistermopper** [comment]
Thanks, the fixer did it.
