### ISSUE TITLE
Mehrere Warnungen im Log

### ISSUE THREAD

**Issue by Schmakus** [arteck/ioBroker.fullybrowser#61]
`

fullybrowser.0 | 2021-12-25 09:10:40.705 | warn | State "fullybrowser.0.192_168_0_41.Info.scopedStorage" has no existing object, this might lead to an error in future versions
-- | -- | -- | --
fullybrowser.0 | 2021-12-25 09:10:40.644 | warn | State "fullybrowser.0.192_168_0_41.Info.BSSID" has no existing object, this might lead to an error in future versions
fullybrowser.0 | 2021-12-25 09:10:40.631 | warn | State "fullybrowser.0.192_168_0_41.Info.packageName" has no existing object, this might lead to an error in future versions
fullybrowser.0 | 2021-12-25 09:09:40.451 | info | State value to set for "fullybrowser.0.192_168_0_41.Info.sensorInfo" has to be stringified but received type "object"
fullybrowser.0 | 2021-12-25 09:09:40.395 | warn | State "fullybrowser.0.192_168_0_41.Info.scopedStorage" has no existing object, this might lead to an error in future versions
fullybrowser.0 | 2021-12-25 09:09:40.319 | warn | State "fullybrowser.0.192_168_0_41.Info.BSSID" has no existing object, this might lead to an error in future versions
fullybrowser.0 | 2021-12-25 09:09:40.305 | warn | State "fullybrowser.0.192_168_0_41.Info.packageName" has no existing object, this might lead to an error in future versions
fullybrowser.0 | 2021-12-25 09:08:40.177 | info | State value to set for "fullybrowser.0.192_168_0_41.Info.sensorInfo" has to be stringified but received type "object"
fullybrowser.0 | 2021-12-25 09:08:40.117 | warn | State "fullybrowser.0.192_168_0_41.Info.scopedStorage" has no existing object, this might lead to an error in future versions
fullybrowser.0 | 2021-12-25 09:08:40.046 | warn | State "fullybrowser.0.192_168_0_41.Info.BSSID" has no existing object, this might lead to an error in future versions
fullybrowser.0 | 2021-12-25 09:08:40.032 | warn | State "fullybrowser.0.192_168_0_41.Info.packageName" has no existing object, this might lead to an error in future versions
fullybrowser.0 | 2021-12-25 09:07:39.833 | info | State value to set for "fullybrowser.0.192_168_0_41.Info.sensorInfo" has to be stringified but received type "object"
fullybrowser.0 | 2021-12-25 09:07:39.759 | warn | State "fullybrowser.0.192_168_0_41.Info.scopedStorage" has no existing object, this might lead to an error in future versions
fullybrowser.0 | 2021-12-25 09:07:39.695 | warn | State "fullybrowser.0.192_168_0_41.Info.BSSID" has no existing object, this might lead to an error in future versions
fullybrowser.0 | 2021-12-25 09:07:39.681 | warn | State "fullybrowser.0.192_168_0_41.Info.packageName" has no existing object, this might lead to an error in future versions
fullybrowser.0 | 2021-12-25 09:06:39.550 | info | State value to set for "fullybrowser.0.192_168_0_41.Info.sensorInfo" has to be stringified but received type "object"
fullybrowser.0 | 2021-12-25 09:06:39.477 | warn | State "fullybrowser.0.192_168_0_41.Info.scopedStorage" has no existing object, this might lead to an error in future versions
fullybrowser.0 | 2021-12-25 09:06:39.359 | warn | State "fullybrowser.0.192_168_0_41.Info.BSSID" has no existing object, this might lead to an error in future versions
fullybrowser.0 | 2021-12-25 09:06:39.346 | warn | State "fullybrowser.0.192_168_0_41.Info.packageName" has no existing object, this might lead to an error in future versions
fullybrowser.0 | 2021-12-25 09:05:39.236 | info | State value to set for "fullybrowser.0.192_168_0_41.Info.sensorInfo" has to be stringified but received type "object"
fullybrowser.0 | 2021-12-25 09:05:39.169 | warn | State "fullybrowser.0.192_168_0_41.Info.scopedStorage" has no existing object, this might lead to an error in future versions
fullybrowser.0 | 2021-12-25 09:05:38.858 | warn | State "fullybrowser.0.192_168_0_41.Info.BSSID" has no existing object, this might lead to an error in future versions
fullybrowser.0 | 2021-12-25 09:05:38.841 | warn | State "fullybrowser.0.192_168_0_41.Info.packageName" has no existing object, this might lead to an error in future versions
fullybrowser.0 | 2021-12-25 09:04:38.592 | info | State value to set for "fullybrowser.0.192_168_0_41.Info.sensorInfo" has to be stringified but received type "object"
fullybrowser.0 | 2021-12-25 09:04:38.522 | warn | State "fullybrowser.0.192_168_0_41.Info.scopedStorage" has no existing object, this might lead to an error in future versions
fullybrowser.0 | 2021-12-25 09:04:38.455 | warn | State "fullybrowser.0.192_168_0_41.Info.BSSID" has no existing object, this might lead to an error in future versions
fullybrowser.0 | 2021-12-25 09:04:38.443 | warn | State "fullybrowser.0.192_168_0_41.Info.packageName" has no existing object, this might lead to an error in future versions
fullybrowser.0 | 2021-12-25 09:03:38.288 | info | State value to set for "fullybrowser.0.192_168_0_41.Info.sensorInfo" has to be stringified but received type "object"
fullybrowser.0 | 2021-12-25 09:03:38.218 | warn | State "fullybrowser.0.192_168_0_41.Info.scopedStorage" has no existing object, this might lead to an error in future versions
fullybrowser.0 | 2021-12-25 09:03:38.143 | warn | State "fullybrowser.0.192_168_0_41.Info.BSSID" has no existing object, this might lead to an error in future versions
fullybrowser.0 | 2021-12-25 09:03:38.125 | warn | State "fullybrowser.0.192_168_0_41.Info.packageName" has no existing object, this might lead to an error in future versions
fullybrowser.0 | 2021-12-25 09:02:37.998 | info | State value to set for "fullybrowser.0.192_168_0_41.Info.sensorInfo" has to be stringified but received type "object"
fullybrowser.0 | 2021-12-25 09:02:37.937 | warn | State "fullybrowser.0.192_168_0_41.Info.scopedStorage" has no existing object, this might lead to an error in future versions

`

v2.0.10
js 3.3.22
node v14.18.2
npm 6.14.15

**Comment by Horgul123** [comment]
Hab das gleiche Problem....  Ähliche Konfig....

**Comment by r3vO88** [comment]
Hier ebenfalls das gleiche Problem....

PLATTFORM: LINUX
BETRIEBSSYSTEM: LINUX
ARCHITEKTUR: X64
CPUS: 4
GESCHWINDIGKEIT: 2001 MHZ
MODELL: INTEL(R) CELERON(R) J4125 CPU @ 2.00GHZ
RAM: 9.5 GB
SYSTEM-BETRIEBSZEIT: 61 T. 03:17:27
NODE.JS: V14.18.1
NPM: 6.14.15

**Comment by arteck** [comment]
lösche mal die Objekte und starte den adapter neu.. 
die werden dann neu richtig erzeugt
