### ISSUE TITLE
updateDeviceERROR bei mehreren Tablets

### ISSUE THREAD

**Issue by pacco81** [arteck/ioBroker.fullybrowser#67]
Hallo liebe Entwickler !

Ich bin mit der Kombination Fully, iobroker, und Galaxy-Tablets als Visu-Hardware sehr zufrieden. Sehr schöne und saubere Lösung insb. mirt Anbindung im iobroker.

Ich nutze FullyKiosk auf 5 baugleichen Androids und bekomme seit ein paar Wochen LogFehler bei allen Geräten im Iobroker
"updateDeviceERROR 10.11.12.83"
 
PING, WebInterface und auch Bedienung der FullyApp über die iobroker Commands funktioniert jedoch einwandfrei. Wo der Log Fehler herkommt weiß ich leider nicht. Bei Bedarf kann ich auch mehr Logs o.Ä. liefern

Funktionell ist bisher alles OK, so dass ich keinen hohen Leidensdruck mit den Logs habe. 

Besten Dank und Gruß !

<img width="1221" alt="Bildschirmfoto 2022-01-19 um 09 05 50" src="https://user-images.githubusercontent.com/29131107/150090454-839f1231-ada1-4f29-9730-08d613ef1321.png">
<img width="577" alt="Bildschirmfoto 2022-01-19 um 09 06 15" src="https://user-images.githubusercontent.com/29131107/150090460-b57db553-815c-4d76-ad74-d11187093523.png">
<img width="1436" alt="Bildschirmfoto 2022-01-19 um 09 06 20" src="https://user-images.githubusercontent.com/29131107/150090462-4131cdf4-20e8-4ff6-9cc4-0f923e605856.png">
<img width="1367" alt="Bildschirmfoto 2022-01-19 um 09 06 51" src="https://user-images.githubusercontent.com/29131107/150090465-6c03d0e3-bff4-4b9b-9c9d-47b86ac556ee.png">
<img width="391" alt="Bildschirmfoto 2022-01-19 um 09 14 45" src="https://user-images.githubusercontent.com/29131107/150090622-951ae33e-50f4-483e-8344-1ac55b366e68.png">
<img width="406" alt="Bildschirmfoto 2022-01-19 um 09 14 52" src="https://user-images.githubusercontent.com/29131107/150090628-74a554a6-a7ae-49bf-9f90-0b89c671c5be.png">
<img width="318" alt="Bildschirmfoto 2022-01-19 um 09 14 58" src="https://user-images.githubusercontent.com/29131107/150090632-9323dbc2-0e1a-4fde-98ff-12943f436309.png">
<img width="652" alt="Bildschirmfoto 2022-01-19 um 09 15 03" src="https://user-images.githubusercontent.com/29131107/150090634-62590dee-edfb-4982-b816-9191f857a6db.png">

**Comment by rmp63526** [comment]
Hi, habe bei meinem Fire HD Tablet 10 das gleiche Problem , bzw. die gleiche Warnmeldung.
Nix wildes soweit, wäre aber interessant was es auslöst.
Kennt man hierzu schon die Ursache?

**Comment by arteck** [comment]
du erwartest dass der request nach 300 ms zurück kommt.. na du bist ja lustig

**Comment by tony63526** [comment]
Also bei mir steht Standardmäßig wenn man die instance installiert nix drin und ich bekomme die Fehlermeldung!
Was ist denn eine vernünftige Zahl, gibt leider zu viele davon.

**Comment by pacco81** [comment]
Habe mal rumprobiert: Egal was ich bei TimeOut einstelle: blank, oder bis zu 90000ms > im Log erscheint sofort und noch vor Ablauf des time-out Intervalls der Fehler:
<img width="776" alt="Bildschirmfoto 2022-01-30 um 18 02 23" src="https://user-images.githubusercontent.com/29131107/151709381-254bd5c1-df30-4ed5-962d-a5263335891c.png">

**Comment by pacco81** [comment]
<img width="410" alt="Bildschirmfoto 2022-01-30 um 18 04 40" src="https://user-images.githubusercontent.com/29131107/151709431-5721ca2a-8e11-4c72-8df3-91d82e3fe23a.png">

**Comment by arteck** [comment]
> Also bei mir steht Standardmäßig wenn man die instance installiert nix drin und ich bekomme die Fehlermeldung! Was ist denn eine vernünftige Zahl, gibt leider zu viele davon.

es gibt keine vernünftige.. das ist von System zu System unterschiedlich..
das timeout besagt in der Zeit MUSS das Gerät antworten .. wenn das nicht der Fall ist dann wird die Meldung geschrieben

**Comment by arteck** [comment]
> <img alt="Bildschirmfoto 2022-01-30 um 18 04 40" width="410" src="https://user-images.githubusercontent.com/29131107/151709431-5721ca2a-8e11-4c72-8df3-91d82e3fe23a.png">

max 10000

**Comment by pacco81** [comment]
Nach dem Update auf 2.0.14  kommt der Fehler jetzt nicht mehr. Besten Dank !
