### ISSUE TITLE
js-controller 4 Meldungen

### ISSUE THREAD

**Issue by Pocky2507** [arteck/ioBroker.fullybrowser#74]
fullybrowser.0 | 2022-02-03 15:04:19.244 | warn | (401967) This object will not be created in future versions. Please report this to the developer.
-- | -- | -- | --
fullybrowser.0 | 2022-02-03 15:04:19.241 | warn | (401967) Object 192_168_123_61.Commands.screenBrightness is invalid: Default value has to be type "number" but received type "string"

**Comment by arteck** [comment]
stop the adapter
del all objects
start 

and all is fine
