### ISSUE TITLE
Meldung nach update js-controller 4.0.14

### ISSUE THREAD

**Issue by JBSullivan** [arteck/ioBroker.fullybrowser#79]
Nicht schlimmes, sondern nur der Wunsch der Meldung, diese an den Entwickler weiter zu melden.

Meldung tauchte erst mit Update auf js-controller 4.0.14 beim Neustart von ioB auf.

`<html>
<body>

fullybrowser.0 | 14184 | 2022-02-20 13:18:48.919 | warn | This object will not be created in future versions. Please report this to the developer.
-- | -- | -- | -- | --
fullybrowser.0 | 14184 | 2022-02-20 13:18:48.919 | warn | Object 10_122_60_62.Commands.screenBrightness is invalid: Default value has to be type "number" but received type "string"

</body>
</html>`

**Comment by arteck** [comment]
https://github.com/arteck/ioBroker.fullybrowser/issues/80
