### ISSUE TITLE
loadURL Problem beim laden einer IoBroker View

### ISSUE THREAD

**Issue by Harald-B-Rupp** [arteck/ioBroker.fullybrowser#8]
Wenn ich in dem Datenpunkt **loadURL** eine IoBroker VIS URL manuell eingebe wird diese nicht geladen.

Das Problem ist das **#** Symbol.

http://ipadresse:8082/vis/index.html#Landing

Wird eine Adresse ohne # Symbol in der URL eingegeben, wird die Seite umgehend geladen.

**Comment by arteck** [comment]
das scheint an der API zu liegen.. da kann ich nichts machen

**Comment by arteck** [comment]
gefixt

**Comment by BassT23** [comment]
Muss das issue leider nochmal aufmachen,
habe gerade genau, das angesprochene Problem.
Wie kann ich es Lösen?
Gruß
