### ISSUE TITLE
2.1.2 - keine Sonderzeichen im Passwort akzeptiert

### ISSUE THREAD

**Issue by djmarc75** [arteck/ioBroker.fullybrowser#94]
Sorry, aber seit der Version 2.1.2 funtionieren bei mir keine Gerätesteuerungen mehr.... hab 8 Android-Geräte inkl. PRO Lizenzen
Bin dann mal wieder auf 2.1.1 zurück.

**Comment by arteck** [comment]
wo sind die LOGS

**Comment by djmarc75** [comment]
Hab des Rätsels Lösung.
Die Version scheint nicht mit Sonderzeichen Im Passwort klarzukommen:

fullybrowser.0 | 2022-04-21 17:06:24.710 | debug | Send xxxx://192.168.178.xx:2323/?cmd=restartApp&password=xxxxundefined%3F
-- | -- | -- | --
fullybrowser.0 | 2022-04-21 17:06:24.707 | debug | stateID fullybrowser.0.192_168_178_xx.Commands.restartApp changed: true (ack = false)

in der ersten Zeile das "undefined" ist eigentlich ein Sonderzeichen.
Habe jetzt mal das PW ohne Sonderzeichen geändert und da klappts auch wieder.

**Comment by Flipperbastler** [comment]
> Hab des Rätsels Lösung - wahrscheinlich. Die Version scheint nicht mit Sonderzeichen Im Passwort klarzukommen:
> fullybrowser.0 	2022-04-21 17:06:24.710 	debug 	Send xxxx://192.168.178.xx:2323/?cmd=restartApp&password=xxxxundefined%3F
> fullybrowser.0 	2022-04-21 17:06:24.707 	debug 	stateID fullybrowser.0.192_168_178_xx.Commands.restartApp changed: true (ack = false)
> 
> in der ersten Zeile das "undefined%3F" sind eigentlich zwei Sonderzeichen. Habe jetzt mal das PW ohne Sonderzeichen geändert und da klappts auch wieder.

Kann ich bestätigen! Habe gerade die Erstinbetriebnahme mit den ersten "Gehversuchen" hinter mir, mit Google-Suche ganz schnell hier die Lösung gefunden! Sonderzeichen entfernt - jetzt alles gut!

**Comment by arteck** [comment]
qurde korrigiert
